#include <stdio.h>
#include <cs50.h>

int main(void)
{
    int h;
    do
    {
        h = get_int("Height: ");
    }
    while(h < 1 || h > 8);
    for(int a = 0; a <= h; a++)
    {
        for(int b = 0; b <= h; b++)
        {
            if(b>(h-a)){
                printf("#");
            }
           
            else{
                printf(" ");
            }
       }
       printf("\n");
    }
}

